namespace :seed do
  desc "Generate activity interests"
  task :seed_interests => :environment do
    interests = [
      "Hiking",
      "Sightseeing",
      "Photography",
      "Food tasting",
      "Local cuisine",
      "Beach activities",
      "Water sports",
      "Adventure sports",
      "Historical sites",
      "Museums",
      "Art galleries",
      "Shopping",
      "Local festivals",
      "Music concerts",
      "Theater performances",
      "Wildlife safari",
      "Boat tours",
      "Wine tasting",
      "Cooking classes",
      "Spa and wellness",
      "Scuba diving",
      "Snorkeling",
      "Skydiving",
      "Paragliding",
      "Hot air balloon rides",
      "Cultural experiences",
      "City tours",
      "Camping",
      "Fishing",
      "Golfing",
      "Skiing",
      "Snowboarding",
      "Amusement parks",
      "Ziplining",
      "Cruise trips",
      "River rafting",
      "Bungee jumping",
      "Horseback riding",
      "Motorcycle tours",
      "Helicopter rides",
      "Volunteering",
      "Language learning",
      "Cooking workshops",
      "Wine tours",
      "Farm visits",
      "Mountain climbing",
      "Cultural performances",
      "Local markets",
      "Street food tours",
      "Cycling tours",
      "Horse racing",
      "Gardens and parks",
      "Archaeological sites",
      "Cave exploration",
      "Bird watching",
      "Sailing",
      "Kayaking",
      "Rock climbing",
      "Surfing",
      "Ski resorts",
      "Theme parks",
      "Water parks",
      "Zoo visits",
      "Botanical gardens",
      "Spice plantations",
      "Tea estates",
      "Desert safaris",
      "Camel rides",
      "Motorbike trips",
      "Cultural festivals",
      "Wine festivals",
      "Beer tasting",
      "Pub crawls",
      "Nightlife experiences",
      "Cooking competitions",
      "Art workshops",
      "Pottery classes",
      "Hiking trails",
      "Nature reserves",
      "Wildlife sanctuaries",
      "Elephant rides",
      "Trekking",
      "Canyoning",
      "Waterfall hikes",
      "Cultural tours",
      "Historical tours",
      "Ghost tours",
      "Cemetery visits",
      "Haunted house visits",
      "Escape rooms",
      "Cycling races",
      "Marathons",
      "Triathlons",
      "Parades",
      "Fireworks displays",
      "Carnivals",
      "Street performances",
      "Bus tours",
      "Train rides",
      "Motorbike rentals",
      "Boat rentals",
      "Car rentals",
      "Scooter rentals",
      "Segway tours",
      "Horse carriage rides",
      "Gondola rides",
      "Ferry rides",
      "Cable car rides",
      "Helicopter tours",
      "Hot air balloon festivals",
      "Kite festivals",
      "Music festivals",
      "Film festivals",
      "Literary festivals",
      "Fashion shows",
      "Art exhibitions",
      "Craft markets",
      "Antique markets",
      "Flea markets",
      "Christmas markets",
      "New Year's Eve celebrations",
      "Cultural dances",
      "Live music performances",
      "Opera shows",
      "Ballet performances",
      "Stand-up comedy shows",
      "Magic shows",
      "Circus performances",
      "Aquarium visits",
      "Planetarium visits",
      "Science museums",
      "Children's museums",
      "Toy museums",
      "Transport museums",
      "Aviation museums",
      "Military museums",
      "Natural history museums",
      "Science centers",
      "Observatories",
      "Botanical parks",
      "Rose gardens",
      "National parks",
      "Wildlife parks",
      "Safari parks",
      "Conservation centers",
      "Butterfly gardens",
      "Bird parks",
      "Reptile parks",
      "Aquatic parks",
      "Waterfall visits",
      "Cave visits",
      "Canyon visits",
      "Mountain biking",
      "Off-roading",
      "Motorcycling",
      "Biking",
      "Horse riding",
      "Sleigh rides",
      "Dog sledding",
      "Ice skating",
      "Snowshoeing",
      "Snowmobiling",
      "Ice climbing",
      "Ice fishing",
      "Ice festivals",
      "Snow festivals",
      "Theme park rides",
      "Water park slides",
      "Zoo safaris",
      "Animal encounters",
      "Botanical tours",
      "Tea tasting",
      "Spice tasting",
      "Desert camping",
      "Stargazing",
      "Sunset cruises",
      "Sunrise hikes",
      "Cultural shows",
      "Historical reenactments",
      "Ghost walks",
      "Wine trails",
      "Beer tours",
      "Pub tours",
      "Nightclub visits",
      "Cooking shows",
      "Art shows",
      "Pottery workshops",
      "Nature walks",
      "Wildlife walks",
      "Elephant sanctuaries",
      "Canyon hikes",
      "Waterfall rappelling",
      "Cultural museums",
      "Historical museums",
      "Cemetery tours",
      "Haunted house tours",
      "Escape games",
      "Cycling events",
      "Marathon races",
      "Triathlon races",
      "Parade floats",
      "Fireworks competitions",
      "Carnival rides",
      "Street buskers",
      "Train journeys",
      "Motorbike tours",
      "Boat cruises",
      "Car road trips",
      "Scooter rides",
      "Segway rentals",
      "Horse carriage tours",
      "Gondola cruises",
      "Ferry trips",
      "Cable car trips",
      "Helicopter rides",
      "Hot air balloon rides",
      "Kite flying",
      "Music concerts",
      "Film screenings",
      "Literary readings",
      "Fashion exhibitions",
      "Art auctions",
      "Craft fairs",
      "Antique fairs",
      "Flea markets",
      "Christmas fairs",
      "New Year's Eve parties",
      "Cultural performances",
      "Live music gigs",
      "Opera concerts",
      "Ballet shows",
      "Stand-up comedy gigs",
      "Magic performances",
      "Circus acts",
      "Aquarium tours",
      "Planetarium shows",
      "Science exhibits",
      "Children's exhibits",
      "Toy exhibits",
      "Transport exhibits",
      "Aviation exhibits",
      "Military exhibits",
      "Natural history exhibits",
      "Science centers",
      "Observatory visits",
      "Botanical gardens",
      "Rose gardens",
      "National parks",
      "Wildlife parks",
      "Safari parks",
      "Conservation centers",
      "Butterfly gardens",
      "Bird parks",
      "Reptile parks",
      "Aquatic parks",
      "Waterfall visits",
      "Cave visits",
      "Canyon visits",
      "Mountain biking",
      "Off-roading",
      "Motorcycling",
      "Biking",
      "Horse riding",
      "Sleigh rides",
      "Dog sledding",
      "Ice skating",
      "Snowshoeing",
      "Snowmobiling",
      "Ice climbing",
      "Ice fishing",
      "Ice festivals",
      "Snow festivals",
      "Theme park rides",
      "Water park slides",
      "Zoo safaris",
      "Animal encounters",
      "Botanical tours",
      "Tea tasting",
      "Spice tasting",
      "Desert camping",
      "Stargazing",
      "Sunset cruises",
      "Sunrise hikes",
      "Cultural shows",
      "Historical reenactments",
      "Ghost walks",
      "Wine trails",
      "Beer tours",
      "Pub tours",
      "Nightclub visits",
      "Cooking shows",
      "Art shows",
      "Pottery workshops",
      "Nature walks",
      "Wildlife walks",
      "Elephant sanctuaries",
      "Canyon hikes",
      "Waterfall rappelling",
      "Cultural museums",
      "Historical museums",
      "Cemetery tours",
      "Haunted house tours",
      "Escape games",
      "Cycling events",
      "Marathon races",
      "Triathlon races",
      "Parade floats",
      "Fireworks competitions",
      "Carnival rides",
      "Street buskers",
      "Train journeys",
      "Motorbike tours",
      "Boat cruises",
      "Car road trips",
      "Scooter rides",
      "Segway rentals",
      "Horse carriage tours",
      "Gondola cruises",
      "Ferry trips",
      "Cable car trips",
      "Helicopter rides",
      "Hot air balloon rides",
      "Kite flying"
    ]

    100.times do
      interest = interests.sample
      Interest.find_or_create_by(name: interest, kind: 'activity')
    end

    puts "Activity interests seeded successfully!"

    locations = [
      "Paris",
      "London",
      "New York",
      "Tokyo",
      "Rome",
      "Barcelona",
      "Sydney",
      "Cape Town",
      "Rio de Janeiro",
      "Dubai",
      "Mumbai",
      "Bangkok",
      "Bali",
      "Istanbul",
      "Prague",
      "Vienna",
      "Amsterdam",
      "Berlin",
      "Moscow",
      "Cairo",
      "Los Angeles",
      "San Francisco",
      "Toronto",
      "Vancouver",
      "Mexico City",
      "Sao Paulo",
      "Buenos Aires",
      "Lima",
      "Santiago",
      "Cusco",
      "Lisbon",
      "Madrid",
      "Athens",
      "Dublin",
      "Edinburgh",
      "Stockholm",
      "Oslo",
      "Copenhagen",
      "Helsinki",
      "Reykjavik",
      "Dubrovnik",
      "Zagreb",
      "Budapest",
      "Warsaw",
      "Brussels",
      "Munich",
      "Venice",
      "Florence",
      "Milan",
      "Seville",
      "Valencia",
      "Porto",
      "Manchester",
      "Belfast",
      "Glasgow",
      "Montreal",
      "Cancun",
      "Kyoto",
      "Osaka",
      "Hiroshima",
      "Nara",
      "Busan",
      "Jeju",
      "Beijing",
      "Shanghai",
      "Hong Kong",
      "Taipei",
      "Phuket",
      "Chiang Mai",
      "Jakarta",
      "Kuala Lumpur",
      "Singapore",
      "Abu Dhabi",
      "Jaipur",
      "Bangalore",
      "Kolkata",
      "Alexandria",
      "Luxor",
      "Aswan",
      "Johannesburg",
      "Durban",
      "Nairobi",
      "Marrakech",
      "Bogota",
      "Cartagena",
      "Quito",
      "Galapagos Islands",
      "Auckland",
      "Wellington",
      "Queenstown",
      "Christchurch",
      "Melbourne",
      "Brisbane",
      "Perth",
      "Adelaide",
      "Great Barrier Reef",
      "Fiji",
      "Tahiti",
      "Hawaii"
    ].uniq

    100.times do
      location = locations.sample
      Interest.find_or_create_by(name: location, kind: 'location')
    end

    puts "Location interests seeded successfully!"
  end
end